name: Build Linux

on:
  workflow_call: 

jobs:
  build-linux:
    name: Build Linux App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.38.3
          channel: 'stable'

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Linux App (Release)
        shell: /usr/bin/bash -e {0}
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.38.3-x64
          PUB_CACHE: /home/runner/.pub-cache
        run: flutter build linux --release

      - name: Upload Linux App Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: linux-release-app
          path: build/linux/x64/release/bundle/
