name: Deploy Builds

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    uses: ./.github/workflows/build_android.yml
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  build-macos:
    name: Build macOS
    uses: ./.github/workflows/build_macos.yml

  build-windows:
    name: Build Windows
    uses: ./.github/workflows/build_windows.yml

  build-ios:
    name: Build iOS
    uses: ./.github/workflows/build_ios.yml

  build-linux:
    name: Build Linux
    uses: ./.github/workflows/build_linux.yml



  release:
    name: Create GitHub Release With Built Artifacts
    runs-on: ubuntu-latest
    needs:
      - build-android
      - build-ios
      - build-macos
      - build-windows
      - build-linux
    steps:
      - name: Download Android APK
        if: needs.build-android.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: app-release-apk
          path: ./android-artifact

      - name: Download Android App Bundle (AAB)
        if: needs.build-android.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: app-release-aab
          path: ./android-artifact

      - name: Download macOS Artifact
        if: needs.build-macos.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: macos-release-app
          path: ./macos-artifact

      - name: Download Windows Release App
        if: needs.build-windows.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: windows-release-app
          path: ./windows-artifact/release

      - name: Download Windows Installer (.exe)
        if: needs.build-windows.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: windows-installer-exe
          path: ./windows-artifact/installer

      - name: Download Windows Installer (.msix)
        if: needs.build-windows.result == 'success'
        uses: actions/download-artifact@v5
        with:
          name: windows-installer-msix
          path: ./windows-artifact/installer

      # - name: Download iOS Artifact
      #   if: needs.build-ios.result == 'success'
      #   uses: actions/download-artifact@v5
      #   with:
      #     name: ios-artifact
      #     path: ./ios-artifact

      - name: Create Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: |
            ./android-artifact/*
            ./macos-artifact/*
            ./windows-artifact/release/**
            ./windows-artifact/installer/**
            # ./ios-artifact/*   # Uncomment if you add iOS artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

